### ISSUE TITLE
Compatibility to Kube Mgmt Project

### ISSUE THREAD

**Issue by mkjoerg** [Foundato/kelon#27]
Kelon should be compatible to the OPA Kube MGMT project, so that it can be integrated very easy in a Kubernetes environment. To support the kube-mgmt binary, Kelon has to integrate the data update API, so that the tool can update the policies.

https://github.com/open-policy-agent/kube-mgmt

**Comment by dcseifert** [comment]
kube-mgmt uses following APIs of OPA which are implemented into Kelon:

* v1-Data
  * POST, PUT, PATCH, DELETE
* v1-Policies
  * PUT, DELETE

!!! v1-Data-POST is the overwritten proxy-method of Kelon which uses parh mapping and throws an error in case of a not configured path !!!

Right now this is no problem, because kube-mgmt has a method for Data-POST in the code base, which is unused :D

@mkjoerg I won't merge for now and we should close/merge the PR for this issue after we verified the setup with kube-mgmt. Right now I will focus on Istio-Integration and Mongo, because I already tested the endpoints via Postman.
